FROM oven/bun:1.4-alpine AS builder

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

RUN DATABASE_URL=postgresql://build:build@localhost:5432/build bun --bun run prisma version
RUN DATABASE_URL=postgresql://build:build@localhost:5432/build bun --bun run prisma generate
RUN DATABASE_URL=postgresql://build:build@localhost:5432/build bun --bun run prisma generate
RUN bun run build

FROM builder as migrator

CMD ["bun", "--bun", "run", "prisma", "migrate", "deploy"]

FROM oven/bun:1.4-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY ../package.json ../bun.lock ./
RUN bun install --frozen-lockfile --prod

COPY prisma ./prisma
COPY prisma.config.ts ./
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["bun", "dist/main.js"]